---
- name: Make sure Redis is installed.
  apt:
    name: "{{ redis_package_name }}"
    state: present
    update_cache: true
    cache_valid_time: 60
  notify:
    - Stop the default redis server
    - Disable the default redis service file

- name: Flush Handlers.
  meta: flush_handlers
