---
- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'


- include: instance-config.yml
  vars:
    redis_port: "{{ item.port }}"
    redis_name: "{{ item.name }}"
    redis_bind: "{{ item.bind }}"
  with_items: "{{ redis_configs }}"
