---
- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'


- include_tasks: instance-config.yml
  with_items: "{{ redis_configs }}"

- name: Install sysfsutils for disabling transparent huge pages
  apt:
    name: sysfsutils
    state: present
    update_cache: true
    cache_valid_time: 60

- name: Disable transparent huge pages for performance
  lineinfile:
    path: /etc/sysfs.conf
    line: /sys/kernel/mm/transparent_hugepage/enabled = never

- name: Tweak overcommit_memmory
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.overcommit_memory = 1

- name: Tweak maxconn
  lineinfile:
    path: /etc/sysctl.conf
    line: net.core.somaxconn=65365
