---
- name: Stop the default redis server
  service: name=redis-server state=stopped

- name: Disable the default redis service file
  service: name=redis-server enabled=false

- name: Reload daemon
  systemd:
    daemon_reload: true

- name: Restart Redis Services
  service: name="redis-{{ item.name }}" state=restarted
  with_items: "{{ redis_configs }}"
