---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ansible-redis-instance-18-08
    image: ubuntu/bionic/amd64
  - name: ansible-redis-instance-16-04
    image: ubuntu/xenial/amd64
  # dont support buster for now - it has issues starting the redis service via systemd
  # - name: ansible-redis-instance-buster
  #   image: debian/buster/amd64
  - name: ansible-redis-instance-stretch
    image: debian/stretch/amd64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
